##### Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for performing complex mathematical operations. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

1. Initializing the NumPy arrays
2. Accessing elements
3. Array types
4. Array Dimensions and Shapes
5. Indexing and Slicing of Matrices
6. Statistics functions
7. Broadcasting and Vectorized operations
8. Useful Numpy functions

In [ ]:
! pip install numpy

In [ ]:
import sys
import numpy as np

The sys module in Python provides various functions and variables that are used to manipulate different parts of the Python runtime environment. It allows operating on the interpreter as it provides access to the variables and functions that interact strongly with the interpreter.

In [ ]:
# Basic Numpy Arrays
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# access the individual elements of array a
a[0], a[1]

(1, 2)

In [ ]:
#access all elements
a[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#access from 2nd till 5th element
a[1:6]

array([2, 3, 4, 5, 6])

In [ ]:
#negative indexing can be used to access elements from the end

a[1:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#array([1,2, 3,  4,  5,  6,  7,  8,  9, 10])
# access the elements step wise [start-index:end-index:step]

a[0:9:2]

array([1, 3, 5, 7, 9])

In [ ]:
# Array Types

a.dtype

dtype('int32')

In [ ]:
b = np.array([0, .5, 1, 1.5, 2])
# 0.0 .0 1.0 1.5 2.0
b.dtype

dtype('float64')

In [ ]:
#change data type

np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [ ]:
# Array Dimensions and shapes

A = np.array([
    [1, 2,5 ],
    [4, 5, 6]
])
A

array([[1, 2, 5],
       [4, 5, 6]])

 Name ID addres
1.mahn 87 hu
2.sara 78 usjx


In [ ]:
# A is an array having 2 rows and 3 columns
A.shape #R x C

(2, 3)

In [ ]:
#check the dimensions of array A

A.ndim

2

In [ ]:
#Check the no. of elements in array A
A.size

6

In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

In [ ]:
#If the shape isn't consistent, it'll just fall back to regular Python objects:

C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\Laptop\AppData\Local\Temp\ipykernel_8412\3613905410.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [ ]:
C.dtype

dtype('O')

In [ ]:
# Indexing and Slicing of Matrices

# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [ ]:
#accessing row 2

A[1]

array([4, 5, 6])

In [ ]:
#accessing elements from row 2
A[1][0]

4

In [ ]:
# [row, col]
#[ ,]
A[1, 1]

5

In [ ]:
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# accessing rows from 0-2, where 2 is not included
#A[0:2]
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# [row start:end, col start:end]
#all rows but oth and 1st indexed columns
A[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
#1st and 2nd index row, 1st and 2nd column index
A[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# accessing only first 2 rows and 2 col

A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
#accessing last columns of first 2 rows

A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#updating values at position A[1]

A[1] = np.array([10, 29, 10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 29, 10],
       [ 7,  8,  9]])

In [ ]:
# update the entire row with a scalar value.

A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 29, 10],
       [99, 99, 99]])

In [ ]:
A[2,0] = 89
A

array([[ 1,  2,  3],
       [10, 29, 10],
       [89, 99, 99]])

In [ ]:
# Statistics Functions

a = np.array([1, 2, 3, 4])

In [ ]:
# add up all values of an array
a.sum()

10

In [ ]:
#calculate mean
a.mean()

2.5

In [ ]:
#calculate standard deviation
a.std()

1.118033988749895

In [ ]:
#calculate variance
a.var()

1.25

In [ ]:
#Example
# s1
#s2
#s3
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])



A.sum()

45

In [ ]:
A.mean()

5.0

In [ ]:
#col wise addition

A.sum(axis=0)

array([100, 130, 112])

In [ ]:
#row wise addition

A.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
#col wise mean

A.mean(axis=0)

# Mean of the first column [1, 4, 7] is (1 + 4 + 7) / 3 = 4.0.
# Mean of the second column [2, 5, 8] is (2 + 5 + 8) / 3 = 5.0.
# Mean of the third column [3, 6, 9] is (3 + 6 + 9) / 3 = 6.0.

array([4., 5., 6.])

In [ ]:
#row wise mean

A.mean(axis=1)

# Mean of the first row [1, 2, 3] is (1 + 2 + 3) / 3 = 2.0.
# Mean of the second row [4, 5, 6] is (4 + 5 + 6) / 3 = 5.0.
# Mean of the third row [7, 8, 9] is (7 + 8 + 9) / 3 = 8.0.

array([2., 5., 8.])

In [ ]:
# Broadcasting and Vectorized operations

# create a NumPy array with sequential integer values ranging from 0 to 3.
a = np.arange(4)

a


array([0, 1, 2, 3])

In [ ]:
#this will add up 10 to all elements of the array
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10


array([ 0, 10, 20, 30])

In [ ]:
# array a remains unchanched as the changes are not assigned to it
a

array([0, 1, 2, 3])

In [ ]:
#equal to a = a + 100
a += 100

In [ ]:
#array is now changed
a

array([100, 101, 102, 103])

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
a + b

array([110, 111, 112, 113])

In [ ]:
a * b

array([1000, 1010, 1020, 1030])

##### Numpy functions

1. random

In [ ]:
A = np.random.random(size=2)

# Generates random numbers from a uniform distribution
# between 0 (inclusive) and 1 (exclusive).
# The argument size specifies the shape of the output array.
# size=2 means it will generate an array with two random values.
A

array([0.587872  , 0.00983794])

In [ ]:
B = np.random.normal(size=2)
# Generates random numbers from a normal (Gaussian) distribution
# with a mean of 0 and a standard deviation of 1 by default.
# The argument size specifies the shape of the output array.
# size=2 means it will generate an array with two random values.
B

array([-0.12701599, -0.1300116 ])

In [ ]:
C = np.random.rand(2, 4)
# Generates random numbers from a uniform distribution between 0 (inclusive) and 1 (exclusive).
# The rand function is typically used to generate random values
# that follow a uniform distribution.
# The argument 2, 4 specifies the shape of the output array.
# 2 rows and 4 columns filled with random values between 0 and 1.
C

array([[0.24487619, 0.80518855, 0.02684775, 0.96090579],
       [0.92669335, 0.55338478, 0.9179031 , 0.95093947]])

In [ ]:
# create an array of 3 rows and 3 columns with random values from 0 to 100

A = np.random.randint(100, size=(3, 3))

In [ ]:
A

array([[85, 98, 65],
       [37, 11, 30],
       [70, 37, 15]])

###### 2. arange

In [ ]:
A = np.arange(10)
# Generates a 1-dimensional array with values from 0 up to,
# but not including, 10.
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
B = np.arange(5, 10)
# Generate a 1-dimensional array with values starting from 5
# and going up to, but not including, 10.
B

array([5, 6, 7, 8, 9])

In [ ]:
C = np.arange(0, 1, .1)
# Generate a sequence of numbers starting from 0 and incrementing by 0.1
# until it reaches a value just less than 1
C

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

##### 3. reshape

In [ ]:
A = np.arange(10).reshape(2, 5)
# creates a 1-dimensional NumPy array with values from 0 to 9 (inclusive),
# then arranges the values into a 2-dimensional array with 2 rows and 5 columns
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
B = np.arange(10).reshape(5, 2)
# creates a 1-dimensional array with values from 0 to 9 (inclusive),
# then arranges the values into a 2-dimensional array with 5 rows and 2 columns
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

##### 4. linspace

In [ ]:
A = np.linspace(0, 1, 5)
# generates 5 evenly spaced values between 0 (inclusive) and 1 (inclusive)
A

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
B = np.linspace(0, 1, 20)
# generates 20 evenly spaced values between 0 (inclusive) and 1 (inclusive).
B

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
C = np.linspace(0, 1, 20, False)
# generates 20 evenly spaced values between 0 (inclusive) and 1,
# but it doesn't include the endpoint (1.0)
C

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

##### 5. zeros, ones, empty

In [ ]:
A = np.zeros(5)
# generates 1D array with five zeros
A

array([0., 0., 0., 0., 0.])

In [ ]:
B = np.zeros((3, 3))
# generates 2D array with 3 rows and 3 columns filled with 0s
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
C = np.ones(5)
# generates 1D array with five ones
C

array([1., 1., 1., 1., 1.])

In [ ]:
D = np.ones((3, 3))
# generates 2D array with 3 rows and 3 columns filled with 1s
D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
E = np.empty(5)
# allocates memory for a 1D array with five elements
# but does not set their values to any specific initial values.
#The values in E will also be uninitialized and may appear as random numbers.
E

array([1., 1., 1., 1., 1.])

In [ ]:
F = np.empty((2, 2))
# 2D array with 2 rows and 2 columns without specific initial values.
# The values in F will also be uninitialized and may appear as random numbers.
F

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

##### 6. identity and eye

In [ ]:
A = np.identity(3)
# An identity matrix is a square matrix where all the diagonal elements are 1,
# and all other elements are 0
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
B = np.eye(3, 3)
# creates a 3x3 identity matrix.
#The np.eye() function allows specifying the number of rows and columns
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
C = np.eye(8, 4)
# creating a non-square identity matrix,
# 8x4 matrix where the diagonal elements are 1, and all other elements are 0.
C

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
D = np.eye(8, 4, k=1)
# creates an 8x4 identity matrix with an offset of 1,
# meaning that the 1's start one position to the right of the main diagonal.
D

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
E = np.eye(8, 4, k=-3)
# creates an 8x4 identity matrix with an offset of -3,
# meaning that the 1's start three positions to the left of the main diagonal.
E

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])